openapi: 3.0.1
info:
  title: Torrent Downloader API
  description: API for downloading torrents using magnet links.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /torrent:
    post:
      summary: Start a new torrent download
      description: Accepts a magnet link and starts downloading the corresponding torrent.
      operationId: startTorrentDownload
      parameters:
        - in: header
          name: Drive-Authorization
          required: true
          description: Access token for the Driver API
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                magnetLink:
                  type: string
                  description: The magnet link of the torrent to be downloaded.
                  example: "magnet:?xt=urn:btih:abc123xyz456"
      responses:
        "200":
          description: Torrent download started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  taskId:
                    type: string
                    description: The ID of the torrent download task.
                    example: "task-12345"
        "400":
          description: Invalid magnet link format
        "500":
          description: Internal server error

  /torrent/{taskId}:
    get:
      summary: Get the status of a torrent download task
      description: Retrieves the status of a specific torrent download using the task ID.
      operationId: getTorrentDownloadStatus
      parameters:
        - name: taskId
          in: path
          required: true
          description: The ID of the torrent download task.
          schema:
            type: string
            example: "task-12345"
      responses:
        "200":
          description: Torrent task status retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  taskId:
                    type: string
                    description: The ID of the torrent download task.
                    example: "task-12345"
                  status:
                    type: string
                    description: Current status of the torrent task.
                    enum:
                      - "queued"
                      - "downloading"
                      - "completed"
                      - "failed"
                    example: "downloading"
                  progress:
                    type: number
                    description: Percentage of the torrent download completed (0-100).
                    example: 50
                  error:
                    type: string
                    description: Any error message, if applicable.
                    example: "Network timeout"
        "404":
          description: Task not found
        "500":
          description: Internal server error

  /torrent/{taskId}/cancel:
    post:
      summary: Cancel an ongoing torrent download
      description: Cancels a torrent download task by task ID.
      operationId: cancelTorrentDownload
      parameters:
        - name: taskId
          in: path
          required: true
          description: The ID of the torrent download task to cancel.
          schema:
            type: string
            example: "task-12345"
      responses:
        "200":
          description: Torrent download canceled successfully
        "404":
          description: Task not found
        "500":
          description: Internal server error

components:
  schemas:
    TorrentTask:
      type: object
      properties:
        taskId:
          type: string
          description: The ID of the torrent download task.
          example: "task-12345"
        status:
          type: string
          description: The current status of the task (queued, downloading, completed, failed).
          enum:
            - "queued"
            - "downloading"
            - "completed"
            - "failed"
          example: "downloading"
        progress:
          type: integer
          description: Download progress in percentage (0-100).
          example: 50
        error:
          type: string
          description: Any error message (if applicable).
          example: "Network timeout"

  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - apiKeyAuth: []
